### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by Elementtair** [xaoseric/fluxbb-site#1]
That's nice works
maybe you could update the readme to  point to the correct site aka http://fluxbb.com.tr/

**Comment by xaoseric** [comment]
fluxbb.com.tr is not the official home page for the project, it was registered 1 year ago. It is fluxbb.org as indicated by the official repository.

https://github.com/fluxbb/fluxbb

**Comment by Elementtair** [comment]
What you're giving is the forum official github.  Fluxbb.org is dead and down for good now.

Was just saying http://fluxbb.com.tr is the page your work is published and not fluxbb-site.github.io as mentionned in readme.md.
